### ISSUE TITLE
Error in quickstart?

### ISSUE THREAD

**Issue by jkteske** [samuelyeewl/specmatch-emp#32]
I get the following error running quickstart.py:
...
Shifting entire spectrum
Running brute-force match, G-star
Matching spectrum
Matching region (5140, 5100)
#---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/Applications/specmatch-emp-master/docs/quickstart.py in <module>()
    138 print("Running brute-force match, G-star")
    139 # code-start-match-G
--> 140 sm_G.match()
    141 
    142 # Plot chi-squared surfaces

specmatchemp/specmatch.py in match(self, wavlim, wavstep, ignore)

specmatchemp/match.py in __init__(self, target, reference, mode, opt)

IndexError: index 0 is out of bounds for axis 0 with size 0

I tried manually specifying WAVLIM, which seemed to get around the issue:

In [41]: sm_G.match(wavlim=(5140,5200))
Matching spectrum
Matching region (5140, 5200)
 
but I don't know why the SpecMatch "default" WAVLIM was 5140 to 5100. Has anyone else come across this issue? Thanks!

**Comment by samuelyeewl** [comment]
Thanks for the feedback! Sorry it's taken so long to get back to you. I made the change to quickstart.py in 6160db3.

For now, it's better to specify the wavlims unless you're using the CLI. A comprehensive fix will be coming in the next update (soon).

**Comment by jkteske** [comment]
Okay, thanks!
